AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of public subnet IDs in the VPC.
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the load balancer.

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DeletionPolicy: Delete
    Properties:
      Name: !Sub "alb-${EnvironmentName}"
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Tags:
        - Key: Name
          Value: !Sub "alb-${EnvironmentName}"

  ALBHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DeletionPolicy: Delete
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '404'
            ContentType: text/plain
            MessageBody: "Not Found"

  #ALBHTTPSListener:
  #  Type: AWS::ElasticLoadBalancingV2::Listener
  #  Properties:
  #    LoadBalancerArn: !Ref ApplicationLoadBalancer
  #    Protocol: HTTPS
  #    Port: 443
  #    DefaultActions:
  #      - Type: fixed-response
  #        FixedResponseConfig:
  #          StatusCode: '404'
  #          ContentType: text/plain
  #          MessageBody: "Not Found"

Outputs:
  LoadBalancerARN:
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub "${EnvironmentName}-LoadBalancerARN"
  LoadBalancerDNSName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${EnvironmentName}-LoadBalancerDNSName"
  LoadBalancerCanonicalHostedZoneID:
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
  HTTPListenerARN:
    Value: !Ref ALBHTTPListener
    Export:
      Name: !Sub "${EnvironmentName}-HTTPListenerARN"
  #HTTPSListenerARN:
  #  Value: !Ref ALBHTTPSListener
  #  Description: The ARN of the HTTPS listener.