AWSTemplateFormatVersion: '2010-09-09'
Description: Launch an EC2 instance in the default VPC.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID in the default VPC.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the security group.
  InstanceType:
    Type: String
    Default: g6.xlarge
    AllowedValues:
      - g5.xlarge
      - g6.xlarge
    Description: EC2 instance type
  AmiId:
    Type: AWS::EC2::Image::Id
    Default: ami-04ae2e82afc9b46c5
    Description: AMI ID for the EC2 instance (default is for us-west-2)
  MyIP:
    Type: String
    Default: 219.104.137.181/32

Resources:
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and Ollama port access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 11434
          ToPort: 11434
          CidrIp: !Ref MyIP
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AmiId
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref InstanceSecurityGroup
          AssociatePublicIpAddress: true
      UserData: !Base64 |
        #!/bin/bash
        yum update -y

        export OLLAMA_MODELS_DIR=/opt/dlami/nvme/ollama
        sudo mkdir -p "$OLLAMA_MODELS_DIR"

        curl -fsSL https://ollama.com/install.sh | sh

        sudo mkdir -p /etc/systemd/system/ollama.service.d
        sudo tee /etc/systemd/system/ollama.service.d/override.conf >/dev/null <<'EOF'
        [Service]
        Environment=OLLAMA_HOST=0.0.0.0:11434
        Environment=OLLAMA_MODELS=/opt/dlami/nvme/ollama
        ExecStartPost=/usr/bin/env bash -lc 'ollama pull gpt-oss:20b || true'
        EOF

        sudo systemctl daemon-reload
        sudo systemctl enable --now ollama

        sudo chown -R ollama:ollama "$OLLAMA_MODELS_DIR"
      Tags:
        - Key: Name
          Value: OLLAMA-Server

Outputs:
  InstanceId:
    Description: The ID of the launched EC2 instance
    Value: !Ref EC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
  LogGroupName:
    Description: CloudWatch Log Group Name for the instance
    Value: !Sub "/ec2/EC2PlaygroundInstance/${EC2Instance}"