AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpnServerCertificateArn:
    Type: String
  VpnClientRootCertificateArn:
    Type: String
  VpnClientCidrBlock:
    Type: String
  ConnectionSubnetId:
    Type: AWS::EC2::Subnet::Id
  ConnectionSubnetId1:
    Type: AWS::EC2::Subnet::Id
  ConnectionTargetNetworkCidr:
    Type: String

Resources:
  VPNClientEndpoint:
    Type: AWS::EC2::ClientVpnEndpoint
    Properties:
      ClientCidrBlock: !Ref VpnClientCidrBlock
      ServerCertificateArn: !Ref VpnServerCertificateArn
      AuthenticationOptions:
        - Type: certificate-authentication
          MutualAuthentication:
            ClientRootCertificateChainArn: !Ref VpnClientRootCertificateArn
      ConnectionLogOptions:
        Enabled: false
      TagSpecifications:
        - ResourceType: client-vpn-endpoint
          Tags:
            - Key: Name
              Value: my-client-vpn
  VPNClientNetworkAssociation:
    Type: AWS::EC2::ClientVpnTargetNetworkAssociation
    Properties:
      ClientVpnEndpointId: !Ref VPNClientEndpoint
      SubnetId: !Ref ConnectionSubnetId
  VPNClientNetworkAssociation1:
    Type: AWS::EC2::ClientVpnTargetNetworkAssociation
    Properties:
      ClientVpnEndpointId: !Ref VPNClientEndpoint
      SubnetId: !Ref ConnectionSubnetId1
  VPNClientAuthorizationRule:
    Type: AWS::EC2::ClientVpnAuthorizationRule
    Properties:
      ClientVpnEndpointId: !Ref VPNClientEndpoint
      TargetNetworkCidr: !Ref ConnectionTargetNetworkCidr
      AuthorizeAllGroups: true