AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow internal traffic
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: "Name"
          Value: !Sub "sg-${EnvironmentName}"

Outputs:
  SecurityGroupId:
    Description: The ID of the Security Group
    Value: !Ref SecurityGroup

  SecurityGroupVpcId:
    Description: The ID of the VPC associated with the Security Group
    Value: !GetAtt SecurityGroup.VpcId

  SecurityGroupGroupName:
    Description: The name of the Security Group
    Value: !GetAtt SecurityGroup.GroupName