AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of public subnet IDs in the VPC.
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the load balancer.
  CertificateArn:
    Type: String
    Default: ""
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID
    Default: ""
  DomainName:
    Type: String
    Description: Domain name for the ALB (e.g., app.example.com)
    Default: ""

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, ""]]
  HasDomainName: !And
    - !Not [!Equals [!Ref DomainName, ""]]
    - !Not [!Equals [!Ref HostedZoneId, ""]]

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "alb-${EnvironmentName}"
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Tags:
        - Key: Name
          Value: !Sub "alb-${EnvironmentName}"

  ALBHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '404'
            ContentType: text/plain
            MessageBody: "Not Found"

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasCertificate
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Certificates:
        - CertificateArn: !Ref CertificateArn
      Protocol: HTTPS
      Port: 443
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '404'
            ContentType: text/plain
            MessageBody: "Not Found"

  ALBDNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasDomainName
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
        EvaluateTargetHealth: true

Outputs:
  LoadBalancerARN:
    Value: !Ref ApplicationLoadBalancer
    Description: The Amazon Resource Name (ARN) of the load balancer.
  LoadBalancerDNSName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Description: The DNS name of the load balancer.
  LoadBalancerCanonicalHostedZoneID:
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Description: The hosted zone ID for the load balancer.
  HTTPListenerARN:
    Value: !Ref ALBHTTPListener
    Description: The ARN of the HTTP listener.
  HTTPSListenerARN:
    Condition: HasCertificate
    Value: !Ref HTTPSListener
    Description: The ARN of the HTTPS listener.
  ALBDomainName:
    Condition: HasDomainName
    Value: !Ref DomainName
    Description: The custom domain name for the ALB.