AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of public subnet IDs in the VPC.
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the load balancer.
  
  # HTTPSリスナー用の設定で使用するSSL証明書のARN
  #CertificateArn:
  #  Type: String
  #  Description: The ARN of the SSL certificate to use for HTTPS.

  # Route53のDNSレコード設定に使用するカスタムドメイン名
  #DomainName:
  #  Type: String
  #  Default: example.com

  # Route53のホストゾーンID（ドメインに対応するホストゾーン）
  #HostedZoneId:
  #  Type: String
  #  Default: Z03876891L8K7CPB7XTHP

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "alb-${EnvironmentName}"
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
      Tags:
        - Key: Name
          Value: !Sub "alb-${EnvironmentName}"

  ALBHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '404'
            ContentType: text/plain
            MessageBody: "Not Found"

  # HTTPSリスナーの設定
  # HTTPSポート(443)でリスニングし、SSL証明書を使ってHTTPS通信を可能にする
  #ALBHTTPSListener:
  #  Type: AWS::ElasticLoadBalancingV2::Listener
  #  Properties:
  #    LoadBalancerArn: !Ref ApplicationLoadBalancer
  #    Certificates:
  #      - CertificateArn: !Ref CertificateArn
  #    Protocol: HTTPS
  #    Port: 443
  #    DefaultActions:
  #      - Type: fixed-response
  #        FixedResponseConfig:
  #          StatusCode: '404'
  #          ContentType: text/plain
  #          MessageBody: "Not Found"
  
  # Route 53のDNSレコードセットの作成
  # 指定したドメイン名とALBのDNS名を紐付け、カスタムドメインでALBにアクセスできるようにする
  #DNSRecordSet:
  #  Type: "AWS::Route53::RecordSet"
  #  Properties:
  #    HostedZoneId: !Ref HostedZoneId
  #    Name: !Ref DomainName
  #    Type: "A"
  #    AliasTarget:
  #      DNSName: !GetAtt ApplicationLoadBalancer.DNSName
  #      HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID

Outputs:
  LoadBalancerARN:
    Value: !Ref ApplicationLoadBalancer
    Description: The Amazon Resource Name (ARN) of the load balancer.
  LoadBalancerDNSName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Description: The DNS name of the load balancer.
  LoadBalancerCanonicalHostedZoneID:
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Description: The hosted zone ID for the load balancer.
  HTTPListenerARN:
    Value: !Ref ALBHTTPListener
    Description: The ARN of the HTTP listener.
  #HTTPSListenerARN:
  #  Value: !Ref ALBHTTPSListener
  #  Description: The ARN of the HTTPS listener.