AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id

Resources:
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "nat-gateway1-eip-${EnvironmentName}"

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "nat-gateway2-eip-${EnvironmentName}"

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub "nat-gateway1-${EnvironmentName}"

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub "nat-gateway2-${EnvironmentName}"

Outputs:
  # Elastic IP Outputs
  NatGateway1EIP:
    Description: The Elastic IP address for NatGateway1
    Value: !Ref NatGateway1EIP

  NatGateway1EIPAllocationId:
    Description: The Allocation ID of the Elastic IP for NatGateway1
    Value: !GetAtt NatGateway1EIP.AllocationId

  NatGateway2EIP:
    Description: The Elastic IP address for NatGateway2
    Value: !Ref NatGateway2EIP

  NatGateway2EIPAllocationId:
    Description: The Allocation ID of the Elastic IP for NatGateway2
    Value: !GetAtt NatGateway2EIP.AllocationId

  # NAT Gateway Outputs
  NatGateway1Id:
    Description: The ID of NatGateway1
    Value: !Ref NatGateway1

  NatGateway1PublicIp:
    Description: The public IP address of NatGateway1
    Value: !GetAtt NatGateway1EIP.PublicIp

  NatGateway2Id:
    Description: The ID of NatGateway2
    Value: !Ref NatGateway2

  NatGateway2PublicIp:
    Description: The public IP address of NatGateway2
    Value: !GetAtt NatGateway2EIP.PublicIp