AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: String
  VpcEndpointIPs:
    Type: CommaDelimitedList
  AlbListenerArn:
    Type: String

Resources:

  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties: 
      Name: 'SampleHttpsTargetGroup'
      TargetType: 'ip'
      Protocol: 'HTTPS'
      Port: 443
      VpcId: !Ref VpcId
      HealthCheckProtocol: 'HTTPS'
      HealthCheckPort: '443'
      HealthCheckPath: '/static/ping/index.html'
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200,403'
      Targets:
        - Id: !Select [0, !Ref VpcEndpointIPs]
          Port: 443
        - Id: !Select [1, !Ref VpcEndpointIPs]
          Port: 443

  AlarmApiListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: 'forward'
          TargetGroupArn: !Ref TargetGroup
      Conditions:
        - Field: 'path-pattern'
          Values:
            - '/static/ping/*'
      ListenerArn: !Ref AlbListenerArn
      Priority: 30