# aws cloudformation deploy  \
#     --stack-name "alb-deployment-stack"  \
#     --template-file ./static-site-alb-template.yaml  \
#     --parameter-overrides  \
#         VpcId="vpc-hogehoge"  \
#         VpcEndpointIPs="hogehoge"  \
#         AlbListenerArn="arn:aws:elasticloadbalancing:ap-northeast-1:hogehoge"  \
#     --region "ap-northeast-1"  

AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: String
  VpcEndpointIPs:
    Type: CommaDelimitedList
  AlbListenerArn:
    Type: String

Resources:
  StaticSiteTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties: 
      Name: 'static-site-target-group'
      TargetType: 'ip'
      Protocol: 'HTTP'
      Port: 80
      VpcId: !Ref VpcId
      HealthCheckProtocol: 'HTTP'
      HealthCheckPort: '80'
      HealthCheckPath: '/s3-static/index.html'
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200,403'
      Targets:
        - Id: !Select [0, !Ref VpcEndpointIPs]
          Port: 80
        - Id: !Select [1, !Ref VpcEndpointIPs]
          Port: 80

  StaticSiteListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: 'forward'
          TargetGroupArn: !Ref StaticSiteTargetGroup
      Conditions:
        - Field: 'path-pattern'
          Values:
            - '/s3-static/*'
      ListenerArn: !Ref AlbListenerArn
      Priority: 30