AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-igw"

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VpcId

Outputs:
  InternetGatewayId:
    Description: The ID of the Internet Gateway
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "${EnvironmentName}-InternetGatewayId"

  InternetGatewayAttachmentVpcId:
    Description: The ID of the VPC attached to the Internet Gateway
    Value: !Ref VpcId
    Export:
      Name: !Sub "${EnvironmentName}-InternetGatewayAttachmentVpcId"

  InternetGatewayAttachmentId:
    Description: The ID of the Internet Gateway attachment
    Value: !Ref InternetGatewayAttachment
    Export:
      Name: !Sub "${EnvironmentName}-InternetGatewayAttachmentId"
