AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
 SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda security group
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-sg"

Outputs:
  SecurityGroupId:
    Description: "The ID of the Lambda security group"
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub "${EnvironmentName}-SecurityGroupId"