AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
        - Key: "Name"
          Value:  !Sub "vpc-${EnvironmentName}"

Outputs:
  VpcId:
    Description: The ID of the VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${EnvironmentName}-VpcId"

  VpcCidrBlock:
    Description: The primary IPv4 CIDR block for the VPC
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub "${EnvironmentName}-VpcCidr"

  VpcCidrBlockAssociations:
    Description: The association IDs of the IPv4 CIDR blocks for the VPC
    Value: !Join [",", !GetAtt VPC.CidrBlockAssociations]
    Export:
      Name: !Sub "${EnvironmentName}-VpcCidrAssoc"

  DefaultNetworkAcl:
    Description: The ID of the default network ACL for the VPC
    Value: !GetAtt VPC.DefaultNetworkAcl
    Export:
      Name: !Sub "${EnvironmentName}-DefaultAcl"

  DefaultSecurityGroup:
    Description: The ID of the default security group for the VPC
    Value: !GetAtt VPC.DefaultSecurityGroup
    Export:
      Name: !Sub "${EnvironmentName}-DefaultSG"