@region=us-east-2
@apigateway-id=5f370zcz94
@apigateway-id=prod
@base=https://{{apigateway-id}}.execute-api.{{region}}.amazonaws.com/{{apigateway-id}}
###
GET {{base}}/test.png

###
GET {{base}}/images/test